env: 'local'
postgres_url: 'postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable'
redis_url: 'redis://localhost:6379/0'
reservation:
  port: 10120
  timeout: 10h
sso:
  secret_key: 'local-secret-key'
  port: 10116
  timeout: 10h
jwt:
  secret: 'my-secret-key'
  refresh_ttl: 15h
  access_ttl: 1h
